//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCManukauTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int DiaryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int CategoryId { get; set; }
        public int ProjectMemberId { get; set; }
        public Nullable<System.DateTime> Time1 { get; set; }
        public Nullable<System.DateTime> Time2 { get; set; }
        public string Notes { get; set; }
        public string Charge { get; set; }
        public Nullable<System.DateTime> XDateTime { get; set; }
        public string Status { get; set; }
    
        public virtual ProjectMember ProjectMember { get; set; }
        public virtual Category Category { get; set; }
    }
}
